on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: Publish

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    timeout-minutes: 10
    steps:
    - name: 'Checkout peace_website repository'
      uses: actions/checkout@v3
      with:
        path: 'peace_website'

    - name: 'Checkout peace repository'
      uses: actions/checkout@v3
      with:
        repository: 'azriel91/peace'
        path: 'peace'

    - name: 'Install Rust'
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown

    - name: 'Install `wasm-pack`'
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: 'Install Graphviz'
      uses: ts-graphviz/setup-graphviz@v1

    # install mdbook
    - name: mdbook Cache
      id: mdbook_cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/mdbook
        key: ${{ runner.os }}-mdbook

    # - name: Install `mdbook`
    #   uses: peaceiris/actions-mdbook@v1
    #   with:
    #     mdbook-version: latest

    # use custom version of mdbook for now
    - name: Install `mdbook`
      run: cargo install mdbook --git https://github.com/azriel91/mdBook.git --branch improvement/code-blocks
      if: steps.mdbook_cache.outputs.cache-hit != 'true'

    # install mdbook-graphviz
    - name: mdbook-graphviz Cache
      id: mdbook_graphviz_cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/mdbook-graphviz
        key: ${{ runner.os }}-mdbook-graphviz

    - name: 'Install `mdbook-graphviz`'
      run: cargo install mdbook-graphviz
      if: steps.mdbook_graphviz_cache.outputs.cache-hit != 'true'

    # build WASM examples
    #
    # Backtrack 3 layers of directories relative to example dir:
    #
    # * examples
    # * peace (repo)
    # * github agent dir
    - name: 'Build WASM examples'
      working-directory: peace
      run: |
        for example in download
        do wasm-pack build \
          --target web \
          --out-dir "../../doc/src/examples/pkg" \
          --release \
          "examples/${example}" \
          --features 'error_reporting'
        done

    # Build and publish book
    #
    # Backtrack 2 layers of directories relative to `doc` directory:
    #
    # * peace (repo)
    # * github agent dir
    - name: Build book
      working-directory: peace
      run: mdbook build doc -d ../../peace_website/static/book

    # We *do* want to include the built wasm files.
    - name: 'Remove WASM artifacts .gitignore'
      working-directory: peace_website
      run: rm -f ./static/book/examples/pkg/.gitignore

    - name: 'Build zola site'
      uses: shalzz/zola-deploy-action@448f43557d06624a326567089b8965c79ba58306
      env:
        BUILD_DIR: peace_website
        PAGES_BRANCH: gh-pages
        # Unnecessary for build only
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHECK_LINKS: true
        BUILD_ONLY: true

  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 10
    steps:
    - name: 'Checkout peace_website repository'
      uses: actions/checkout@v3
      with:
        path: 'peace_website'

    - name: 'Checkout peace repository'
      uses: actions/checkout@v3
      with:
        repository: 'azriel91/peace'
        path: 'peace'

    - name: 'Install Rust'
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown

    - name: 'Install `wasm-pack`'
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: 'Install Graphviz'
      uses: ts-graphviz/setup-graphviz@v1

    # install mdbook
    - name: mdbook Cache
      id: mdbook_cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/mdbook
        key: ${{ runner.os }}-mdbook

    # - name: Install `mdbook`
    #   uses: peaceiris/actions-mdbook@v1
    #   with:
    #     mdbook-version: latest

    # use custom version of mdbook for now
    - name: Install `mdbook`
      run: cargo install mdbook --git https://github.com/azriel91/mdBook.git --branch improvement/code-blocks
      if: steps.mdbook_cache.outputs.cache-hit != 'true'

    # install mdbook-graphviz
    - name: mdbook-graphviz Cache
      id: mdbook_graphviz_cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/mdbook-graphviz
        key: ${{ runner.os }}-mdbook-graphviz

    - name: 'Install `mdbook-graphviz`'
      run: cargo install mdbook-graphviz
      if: steps.mdbook_graphviz_cache.outputs.cache-hit != 'true'

    # build WASM examples
    #
    # Backtrack 3 layers of directories relative to example dir:
    #
    # * examples
    # * peace (repo)
    # * github agent dir
    - name: 'Build WASM examples'
      working-directory: peace
      run: |
        for example in download
        do wasm-pack build \
          --target web \
          --out-dir "../../doc/src/examples/pkg" \
          --release \
          "examples/${example}" \
          --features 'error_reporting'
        done

    # Build and publish book
    #
    # Backtrack 2 layers of directories relative to `doc` directory:
    #
    # * peace (repo)
    # * github agent dir
    - name: Build book
      working-directory: peace_website
      run: mdbook build ../peace/doc -d ../../peace_website/static/book

    # We *do* want to include the built wasm files.
    - name: 'Remove WASM artifacts .gitignore'
      working-directory: peace_website
      run: rm -f ./static/book/examples/pkg/.gitignore

    - name: 'Build zola site and deploy'
      uses: shalzz/zola-deploy-action@448f43557d06624a326567089b8965c79ba58306
      env:
        BUILD_DIR: peace_website
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHECK_LINKS: true
