on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    timeout-minutes: 10
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'build'
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          PAGES_BRANCH: gh-pages
          CHECK_LINKS: true
          BUILD_ONLY: true

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 10
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_LINKS: true
